"""autogenerated by genmsg_py from LaserBlob.msg. Do not edit."""
import roslib.message
import struct


class LaserBlob(roslib.message.Message):
  _md5sum = "dd2640051bd6d88ca43168b7ae6d7c3a"
  _type = "this_robot/LaserBlob"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 start
int32 end
float32 distance
float32 width
float32 angle

"""
  __slots__ = ['start','end','distance','width','angle']
  _slot_types = ['int32','int32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       start,end,distance,width,angle
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(LaserBlob, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.start is None:
        self.start = 0
      if self.end is None:
        self.end = 0
      if self.distance is None:
        self.distance = 0.
      if self.width is None:
        self.width = 0.
      if self.angle is None:
        self.angle = 0.
    else:
      self.start = 0
      self.end = 0
      self.distance = 0.
      self.width = 0.
      self.angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2i3f.pack(_x.start, _x.end, _x.distance, _x.width, _x.angle))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.start, _x.end, _x.distance, _x.width, _x.angle,) = _struct_2i3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2i3f.pack(_x.start, _x.end, _x.distance, _x.width, _x.angle))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.start, _x.end, _x.distance, _x.width, _x.angle,) = _struct_2i3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2i3f = struct.Struct("<2i3f")
