map_type: costmap
transform_tolerance: 1.5
obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.3
inflation_radius: 0.5

observation_sources: laser_scan

laser_scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, expected_update_rate: .15, observation_persistence: 0.0, marking: true, clearing: true}
